### ISSUE TITLE
Remove the "Flag" feature

### ISSUE THREAD

**Issue by BillyZac** [BillyZac/ganachakra#13]
Maybe. This is meant to flag problematic comments. I think we have other ways of dealing with this.

**Comment by BillyZac** [comment]
I removed this for comments (I think) but I couldn't figure out how to remove it for topics.

**Comment by JeffryGonzalez** [comment]
Yeah, I agree. remove it. I think it might be ok for topics because someone could say "this should be in a tantrika restricted category" or something, right?

**Comment by BillyZac** [comment]
Okay, cool. As of right now, you can "like" and "bookmark" a post. And you can "flag" a topic. It sounds like that's where we want to be, so I'll close the issue.
